
global_frame: /map
robot_base_frame: base_footprint
update_frequency: 5.0
publish_frequency: 1.0


#set to true if you want to initialize the costmap from a static map
static_map: true


transform_tolerance: 0.3
footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]

observation_sources: rfid_read laser_scan_sensor
laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}
rfid_read: {data_type: rfid_node/TagData, sensor_frame: base_footprint, clearing: false, marking: true, topic: /lastTag}

plugins: 
  - {name: tags_layer,        type: "rfid_sensor_layer::RFIDSensorLayer"}
  - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}
