TrajectoryPlannerROS:
  max_vel_x: 0.125
  min_vel_x: 0.05
  max_vel_theta: 0.005
  min_in_place_vel_theta: 0.005

  acc_lim_theta: 1.6
  acc_lim_x: 1.25
  acc_lim_y: 1.25

  holonomic_robot: false

  meter_scoring: true
